### ISSUE TITLE
error when using dojo(AMD) directly load d3-contour from local file

### ISSUE THREAD

**Issue by CordyChen** [d3/d3-contour#11]
When using dojo(AMD) in my project to require d3-contour.js as the local file, the browser has error like this:
![default](https://cloud.githubusercontent.com/assets/22293410/25806444/bfd84fa2-3435-11e7-86cb-7982412f3260.png)
Is it the problem of using AMD requiring d3-contour? Looking forward to your reply...

**Comment by mbostock** [comment]
d3-contour has a dependency on d3-array, so if you’re using an AMD loader, you’ll need to tell it where to find the d3-array module. (See also [d3-require](https://github.com/d3/d3-require), which defaults to loading from [unpkg](https://unpkg.com).)
