### ISSUE TITLE
Options to disable nice thresholds

### ISSUE THREAD

**Issue by domoritz** [d3/d3-contour#15]
I would like to be able to generate a specific number of contours without using nice thresholds. this would be useful to avoid problems like having no contour lines if the number of thresholds is set too low. See https://github.com/vega/vega-geo/issues/4

**Comment by mbostock** [comment]
You can do this by passing an array of thresholds to [*contours*.thresholds](https://github.com/d3/d3-contour/blob/master/README.md#contours_thresholds). For example:

```js
contours.thresholds(d3.quantize(d3.interpolate(min, max), k));
```

Or equivalently:

```js
contours.thresholds(d3.range(k).map(i => min + (max - min) * i / (k - 1)));
```

Alternatively you can pass a function to *contours*.thresholds, which is then invoked with the array of grid *values* and returns the array of thresholds. So you could do something like:

```js
function quantize(k) {
  return function(values) {
    var x0 = min(values), dx = max(values) - x0;
    return range(k).map(i => x0 + dx * i / (k - 1));
  };
}
```

And then:

```js
contours.threshold(quantize(10));
```

So, I don’t think anything needs to be done here.
