### ISSUE TITLE
Large example images are included in the release project

### ISSUE THREAD

**Issue by nyurik** [d3/d3-contour#20]
Hi, the build system for several systems, like Kibana and Wikimedia nodejs, packages the entire node_modules/ into a single file. I was inspecting my node_modules, and I noticed that d3-countour is 5.8MB, even though the code is only a few KB.  I seriously doubt that the images, such as a 1.6MB animated volcano.gif, should be included, re-downloaded for every npm install, and published.   Would it be possible to move it to a demo website instead?  Thanks!!!

**Comment by nyurik** [comment]
Update:  I think the easiest solution would be to move the entire `/img` dir to a new `gh-pages` branch (which should be empty otherwise), and remove it from master branch. Afterwards, just flip the [settings switch to gh-pages](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#enabling-github-pages-to-publish-your-site-from-master-or-gh-pages), and modify the readme to point to the published images there.

**Comment by mbostock** [comment]
Please send me a pull request to add `img/` to [.npmignore](https://github.com/d3/d3-contour/blob/master/.npmignore) to fix this issue.

**Comment by nyurik** [comment]
@mbostock sure, but I cannot move the `img/` files to a new branch that doesn't exist - only you can create `gh-pages` branch.

**Comment by nyurik** [comment]
OOps, sorry, my mistake, accidentally added it to .gitignore, sorry.
