### ISSUE TITLE
Density contour being clipped?

### ISSUE THREAD

**Issue by fredhohman** [d3/d3-contour#24]
I'm running into a peculiar problem when using `contourDensity()` to draw a rather basic density estimation around a set of points. It appears my contour lines are being "clipped"?

<img width="532" alt="ex1" src="https://user-images.githubusercontent.com/5741691/37307982-f7859a66-2612-11e8-91f2-25fb4c6ecd90.png">
<img width="532" alt="ex2" src="https://user-images.githubusercontent.com/5741691/37307987-fa828396-2612-11e8-8615-e96b231875f2.png">

I closely followed [this example](https://bl.ocks.org/mbostock/e3f4376d54e02d5d43ae32a7cf0e6aa9), and my code does not differ by much. Here's my relevant code:

```
g.insert("g", "g")
    .attr("fill", "none")
    .attr("stroke", 'black')
    .attr("stroke-linejoin", "round")
    .selectAll("path")
    .data(contour.contourDensity()
        .x(function (d) { return d.fdx; })
        .y(function (d) { return d.fdy; })
        .bandwidth(80)
        .thresholds(3)
        (selectedNodesData))
    .enter().append("path")
    .attr("d", d3.geoPath())
    .attr("fill", function (d) { return '#eeeeee' })
```

Changing the `.bandwidth()` parameter makes the contours larger (extending beyond the above clip), but the new contours still clip at other positions.

Any suggestions welcomed, thank you!

**Comment by mbostock** [comment]
You need to set [*density*.size](https://github.com/d3/d3-contour/blob/master/README.md#density_size); this defines the rectangular extent in which the estimated density contours are valid. Note that currently the top-left corner of the extent is always [0, 0], which means you may need to translate your data to fit within the extent. It would be nice in the future to replace *density*.size with *density*.extent that takes [[x0, y0], [x1, y1]].

**Comment by fredhohman** [comment]
Hi @mbostock, thanks for the quick response. 

Sure enough, I translated the data to be all positive values and then translated the drawn contour backwards to be centered at (0,0) and it seems to have worked.

Thank you!

**Comment by rodighiero** [comment]
I applied a translation that works. However, computation is high to use contours for animation and I have the feeling that something is still wrong. Please help!

[Repository](https://github.com/rodighiero/LexicalNetwork)
[Preview](https://rodighiero.github.io/LexicalNetwork/)

```
import * as d3 from 'd3'
import { s } from './state'

const z = { x: 0, y: 0, k: 0 }

const _computeDensityData = () => {

    const ex = d3.extent(s.graph.nodes, d => d.x),
        ey = d3.extent(s.graph.nodes, d => d.y),
        em = Math.max(ex[1] - ex[0], ey[1] - ey[0])

    // const w = 4 * s.screen.width; // definition of the grid for the contours
    const width = ex[1] - ex[0]
    const height = ey[1] - ey[0]
    
    z.k = width / em
    z.x = -ex[0] * z.k
    z.y = -ey[0] * z.k

    s.densityData = d3.contourDensity()
        .x(d => z.x + d.x * z.k)
        .y(d => z.y + d.y * z.k)
        .weight(d => d.docs)
        .size([width, height])
        .cellSize(1) // Crispness (1 = best resolution)
        .bandwidth(20) // Expansion of reliefs (40 = high simplification)
        .thresholds(10) // Indicative number of levels
        (s.graph.nodes)

    s.densityData.forEach(d => d.coordinates = d.coordinates
        .map(d => d.map(d => d.map(
            d => [(d[0] - z.x) / z.k, (d[1] - z.y) / z.k]
        )))
    )
}

const color = d3.rgb(251, 253, 166)

export default () => {

    if (s.end && !s.densityData.length) _computeDensityData()
    // _computeDensityData()
    const path = d3.geoPath().context(s.context)

    s.densityData
        .forEach((level, i) => {
            s.context.beginPath()
            s.context.strokeStyle = color
            s.context.lineWidth = (.8 + (.1 * i))
            path(level)
            s.context.stroke()
        })

}
```
