### ISSUE TITLE
contour problems at antimeridian line

### ISSUE THREAD

**Issue by PBrockmann** [d3/d3-contour#25]
Starting from GeoTIFF Contours II (https://bl.ocks.org/mbostock/83c0be21dba7602ee14982b020b12f51), I have tested direct reading from netCDF files (the standard of all Climate Models from IPCC and all Earth System Modeling community). See https://github.com/PBrockmann/D3_netcdfjs and try netcdfjs_05.html

It sounds very promissing. So a great great thank for this d3.contour module !
In my dreams, I would also like to get a raster pixels rendering as in http://geoexamples.com/d3-raster-tools-docs/code_samples/raster-pixels-page.html but that is another story. Is there an official d3 to do that BTW ?

The problem with d3.countour in a geo context is that some contours at antemeridian line are shifted either up or down.
See:
![image](https://user-images.githubusercontent.com/5402758/37603274-82214d3e-2b8e-11e8-89e8-b6cc6b437253.png)
The map get from netcdfjs_05.html is zoomable so the problem can clearly be seen.

I haven't been able to find where this shift comes from ?

Any help welcomed on this topic that could help a huge community.

**Comment by mbostock** [comment]
My guess is that the shift comes from beveling at the edges #4 because the contour algorithm must contain the polygon with the grid. In GeoTIFF Contours II, I map x = [0, n - 1] in the source raster to [-180, +180]. Is it possible you’re mapping from x = [0, n] instead?

**Comment by PBrockmann** [comment]
No I don't do that and moreover I have also noticed the problem directly from the GeoTIFF Contours II.
See d3_contours_01.html in my repository that is a copy of this example and rotate the projection to see the problem. It appears, less visible than from my field but present.
I will capture an image tomorrow. Thank for your interest in this issue.

**Comment by PBrockmann** [comment]
Here a capture from the GeoTIFF Contours II example.
![image](https://user-images.githubusercontent.com/5402758/37617126-6910733c-2bb2-11e8-91c6-3d96e5de38c2.png)

**Comment by PBrockmann** [comment]
It might be a problem relative to normalizePoint from d3-geo-projection ?

**Comment by PBrockmann** [comment]
Try to analyze this problem. The geoStitch algorithm does not correct the fact that the 2 polygons are only one. So the small up and down stiches should not be there.

![image](https://user-images.githubusercontent.com/5402758/37916570-723fddd4-311c-11e8-9036-9e3ce5121618.png)

**Comment by PBrockmann** [comment]
The geoStitch does not correct the antimeridian cut on a polygon. It left 2 small stitches.

![image](https://user-images.githubusercontent.com/5402758/37916714-d94d3da0-311c-11e8-8b30-6dcb5798f44c.png)

**Comment by PBrockmann** [comment]
aaaa

**Comment by PBrockmann** [comment]
Fighting to patch rings from those small uncorrect path at antimeridian line. But without success when d3.contours().smooth(true) is used anyway.
Any idea ?

**Comment by Fil** [comment]
<img width="202" alt="capture d ecran 2018-03-31 a 00 32 05" src="https://user-images.githubusercontent.com/7001/38156009-49a3ce14-347b-11e8-817b-7168e3f77f9e.png">

my solution is to remove the shared points from the stitched polygons
https://github.com/PBrockmann/D3_netcdfjs/pull/1

**Comment by mbostock** [comment]
Updated example: https://observablehq.com/@d3/geotiff-contours-ii
