### ISSUE TITLE
Weighted points in density

### ISSUE THREAD

**Issue by darwinzer0** [d3/d3-contour#28]
It would be great to add an option for entering weighted points in the density function.  I think it would just be a matter of having a weight function that passes in the weights for each data point and adjusting line 35 accordingly:

        values0[xi + yi * n] = values0[xi + yi * n] + weight(d, i, data);

default could be 1.

**Comment by mbostock** [comment]
Fixed in #29; released in 1.3.0.

**Comment by darwinzer0** [comment]
thanks!
