### ISSUE TITLE
Tile border

### ISSUE THREAD

**Issue by olup** [d3/d3-contour#30]
Hey !
Its more a question than an issue : I am using this excellent librairy to produce contour line over elevation data PNG tiles. However, I'd like to produce my contour lines tile-based, so i work one tile at a time. The librairy produces polygones that i transform to multiLineString afterwards. But the problem remains that the line run along the border of the tiles (wich is to be expected). I am having a hard time finding a way to reduce the output to lines going from border to border, but not framing the tile. Any idea about how to get about it ? Cheers !

**Comment by mbostock** [comment]
I’m not sure how to fix this but I welcome ideas!
