### ISSUE TITLE
Tests cases are slightly misleading ?

### ISSUE THREAD

**Issue by mthh** [d3/d3-contour#31]
In the documentation and in the blocks examples the  `size` property of the contour generator created by `d3.contours()` is set such as `[n, m]` where n*m is equal to length of the input array used with the `contour` object.
In the test file the input array counts 110 values but the `size` used is `[10, 10]`.

Is it voluntary ? Or I am missing something ?
Even if it won't change anything to the result, maybe it should be fixed (for clarity) either by removing the last line of the input array or either by using `[10, 11]` as input value for `size` ?

**Comment by mbostock** [comment]
Think it was just a mistake?
