### ISSUE TITLE
Release d3-array v2 compatible version?

### ISSUE THREAD

**Issue by jheer** [d3/d3-contour#34]
It would be wonderful to have a version of d3-contour that works with d3-array v2 to avoid multiple version issues in downstream projects. It looks like the package.json file would need to be updated to support multiple major versions. Thanks!

**Comment by mbostock** [comment]
As noted in the equivalent issue with d3-geo, this will require a major version bump because d3-array@2 introduces a dependency on ES2015+ syntax.

**Comment by mbostock** [comment]
Fixed in 2.0.0.
