### ISSUE TITLE
output data has index which is not exist in input data

### ISSUE THREAD

**Issue by chinesejar** [d3/d3-contour#38]
the input list data which is long as 10000 only contains numbers as follow:
```
[
  -32768, 0, 1,
      13, 6, 7,
       8, 9
]
```
and the theshold is [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]
while the output polygons contains value 10/11/12. 
the length of the output polygons which value is 10/11/12 is the same as the length of polygons which value is 9.
Is it a bug? how get the output without 10/11/12?

**Comment by Fil** [comment]
It doesn't seem to be a bug, the thresholds are levels that separate values. For example if you have an data set with values [1, -1, 1, -1………], with 1 = land and -1 = sea, you can have a threshold = 0 that creates a shore line.

If I didn't understand your question, please feel free to comment with details and possibly a reproducible test case.

**Comment by Fil** [comment]
It doesn't seem to be a bug, the thresholds are levels that separate values. For example if you have an data set with values [1, -1, 1, -1………], with 1 = land and -1 = sea, you can have a threshold = 0 that creates a shore line.

If I didn't understand your question, please feel free to comment with details and possibly a reproducible test case.
