### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by SteveOW** [d3/d3-contour#50]
Hi, 

I am trying to use your library (with THREE.js).  

I tried to run the example javascript code inside an HTML file with the line:
<script src="https://d3js.org/d3-contour.v1.min.js"></script>

At the line: 
var contours = d3.contours()
    .size([n, m])
    .thresholds(d3.range(2, 21).map(p => Math.pow(2, p)))
    (values);

I got the error message: "TypeError: d3.range is not a function".

I guess I need to link another library?

**Comment by Fil** [comment]
Yes in that case you would need to add `<script src="https://d3js.org/d3-array.v2.min.js"></script>`

We should the README and replace d3.range by native JS:
`Array.from({ length: 19 }, (_, i) => Math.pow(2, i + 2))`

**Comment by SteveOW** [comment]
@Fil 

Thanks very much.

It works now when I link in the d3-array.v2.min.js  file.

**Comment by Fil** [comment]
I managed to make a mistake when updating README: https://github.com/d3/d3-contour/commit/8b837a96f750d2b82e79726dae9f694c63593aed
