### ISSUE TITLE
Convenience function for computing a single contour?

### ISSUE THREAD

**Issue by mbostock** [d3/d3-contour#6]
A convenience function for computing a single contour. Like this, but without clobbering *contours*.thresholds:

```js
contours.contour = function(values, threshold) {
  return contours.thresholds([threshold])(values)[0];
};
```

**Comment by michange** [comment]
Is it possible to make it async so that we unfreeze the browser UI and can report progress when processing large datasets ?

**Comment by mbostock** [comment]
> Is it possible to make it async so that we unfreeze the browser UI and can report progress when processing large datasets ?

Yes, you can use a web worker to make compute nonblocking in the UI.
