### ISSUE TITLE
[feature]: cellSize(0.5) would work well in d3.contourDensity()

### ISSUE THREAD

**Issue by kkdd** [d3/d3-contour#63]
Hello,
I would like that ```cellSize(0.5)``` would work well in ```d3.contourDensity()```.
Because I'm not satisfied ```cellSize(1)``` when confirming the following angulated example:

<img src="https://user-images.githubusercontent.com/5372642/186252892-1d46a29a-82e1-42a1-8064-f93c80f12828.jpg" width="400px">

```
const contourDensity = d3.contourDensity()
		    .x(d => d.x)
		    .y(d => d.y)
		    .size([width, height])
		    .cellSize(1)
		    .bandwidth(1)
		    .thresholds(10);
```

**Comment by Fil** [comment]
The cell size must be an integer power of two.

A way you could address the issue in your case is to scale up the data, say by doing
`.x(d => 2 * d.x).y(d => 2 * d.y)`

and then scale down the contours.
