### ISSUE TITLE
what's the difference between this and conrec.js

### ISSUE THREAD

**Issue by jackielii** [d3/d3-contour#9]
what's the difference between this and [conrec.js](https://github.com/jasondavies/conrec.js)?

Thanks

**Comment by mbostock** [comment]
They are different libraries, written by different authors, with different algorithms and different interfaces. You can get a little context in d3/d3#39. There is a comparison in 2015 here (predating this library): http://emptypipes.org/2015/07/22/contour-comparison/ I’ve reproduced the test case in that comparison here: https://bl.ocks.org/mbostock/4606548f571791098f2b97689f662d06

**Comment by jackielii** [comment]
Thanks so much for taking time to make this detailed answer.

Best Regards,
